### ISSUE TITLE
Vertical align cannot be changed

### ISSUE THREAD

**Issue by hankhsiao** [yahoo/grunt-atomizer#11]
I got 
```
'vertical-align':{
    custom: [
        {suffix: 'c', values: ['YOUR-CUSTOM-VALUE']}
    ]
}
```
And then I tried to put it in my custom configuration, I got
Warning: Custom has been passed but it is not allowed for this rule. Config key: vertical-align.

**Comment by src-code** [comment]
@hankhsiao This is actually an issue for atomizer (https://github.com/yahoo/atomizer), not grunt-atomizer.  I'll go ahead and fix the ruleset over there.

**Comment by hankhsiao** [comment]
I see thank you. As well as Ovs-t.

**Comment by src-code** [comment]
@hankhsiao `Ovs-*` is for `-webkit-overflow-scrolling`, which I don't believe supports custom values.  Currently atomizer supports `a` (auto), `inh` (inherit) and `touch` (touch) as suffixes for `.Ovs-`

**Comment by hankhsiao** [comment]
I also got a prompt saying I need to put custom values. And no, it doesn't support custom values.

**Comment by src-code** [comment]
@hankhsiao Perhaps because you tried using `t`, which isn't valid?  It might've thought you were trying to use a custom value... try `touch` and see if that fixes it?

**Comment by src-code** [comment]
fyi https://github.com/yahoo/atomizer/pull/61

**Comment by hankhsiao** [comment]
Thanks
